services:
  amphion:
    build: ./containers/amphion
    ports:
      - "8001:8001"
    environment:
      - port=8001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  bark:
    build: ./containers/bark
    ports:
      - "8002:8002"
    environment:
      - port=8002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  fish:
    build: ./containers/fish
    ports:
      - "8003:8003"
    environment:
      - port=8003
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  styletts2:
    build: ./containers/styletts2
    ports:
      - "8004:8004"
    environment:
      - port=8004
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  parlertts:
    build: ./containers/parlertts
    ports:
      - "8005:8005"
    environment:
      - port=8005
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tortoise:
    build: ./containers/tortoise
    ports:
      - "8006:8006"
    environment:
      - port=8006
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  hierspeechpp:
    build: ./containers/hierspeechpp
    ports:
      - "8007:8007"
    environment:
      - port=8007
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  orchestrator:
    build: ./orchestrator
    depends_on:
      - amphion
    ports:
      - "7860:7860"
    links:
      - amphion
    volumes:
      - type: bind
        source: ./last_selection.txt
        target: /app/last_selection.txt