services:
  amphion:
    build: ./containers/amphion
    ports:
      - "8001:8001"
    environment:
      - port=8001
  orchestrator:
    build: ./orchestrator
    depends_on:
      - amphion
    ports:
      - "7860:7860"
    links:
      - amphion