services:
  amphion:
    build: ./containers/amphion
    ports:
      - "8001:8001"
    environment:
      - port=8001
  # bark:
  #   build: ./containers/bark
  #   ports:
  #     - "8002:8002"
  #   environment:
  #     - port=8002
  # fish:
  #   build: ./containers/fish
  #   ports:
  #     - "8003:8003"
  #   environment:
  #     - port=8003
  # styletts2:
  #   build: ./containers/styletts2
  #   ports:
  #     - "8004:8004"
  #   environment:
  #     - port=8004
  # parlertts:
  #   build: ./containers/parlertts
  #   ports:
  #     - "8005:8005"
  #   environment:
  #     - port=8005
  # tortoise:
  #   build: ./containers/tortoise
  #   ports:
  #     - "8006:8006"
  #   environment:
  #     - port=8006
  # hierspeechpp:
  #   build: ./containers/hierspeechpp
  #   ports:
  #     - "8007:8007"
  #   environment:
  #     - port=8007
  # openvoice:
  #   build: ./containers/openvoice
  #   ports:
  #     - "8008:8008"
  #   environment:
  #     - port=8008
  # pheme:
  #   build: ./containers/pheme
  #   ports:
  #     - "8009:8009"
  #   environment:
  #     - port=8009
  # whisperspeech:
  #   build: ./containers/whisperspeech
  #   ports:
  #     - "8010:8010"
  #   environment:
  #     - port=8010
  #   env_file:
  #     - .env
  # metavoice:
  #   build: ./containers/metavoice
  #   ports:
  #     - "8011:8011"
  #   environment:
  #     - port=8011
  # voicecraft:
  #   build: ./containers/voicecraft
  #   ports:
  #     - "8012:8012"
  #   environment:
  #     - port=8012
  orchestrator:
    build: ./orchestrator
    ports:
      - "7860:7860"
    volumes:
      - type: bind
        source: ./last_selection.txt
        target: /app/last_selection.txt