services:
  amphion:
    build: ./containers/amphion
    ports:
      - "8001:8001"
    environment:
      - port=8001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  bark:
    build: ./containers/bark
    ports:
      - "8002:8002"
    environment:
      - port=8002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  orchestrator:
    build: ./orchestrator
    depends_on:
      - amphion
    ports:
      - "7860:7860"
    links:
      - amphion
    volumes:
      - type: bind
        source: ./last_selection.txt
        target: /app/last_selection.txt