---
provider_name: amphion
systems:
  - valle:
    display_name: "VALL-E"
    paper: "https://arxiv.org/abs/2301.02111"
    training_data: LibriLight
    languages:
      - en
    training_hours: 60000
    num_parameters: 300-400M
    representations:
      - audio codec
      - encodec
    features:
      - non-autoregressive
      - autoregressive
      - grapheme-to-phoneme
      - language modeling
    citations: >
      @inproceedings{zhang2024amphion,
          author={Zhang, Xueyao and Xue, Liumeng and Gu, Yicheng and Wang, Yuancheng and Li, Jiaqi and He, Haorui and Wang, Chaoren and Song, Ting and Chen, Xi and Fang, Zihao and Chen, Haopeng and Zhang, Junan and Tang, Tze Ying and Zou, Lexiao and Wang, Mingxuan and Han, Jun and Chen, Kai and Li, Haizhou and Wu, Zhizheng},
          title={Amphion: An Open-Source Audio, Music and Speech Generation Toolkit},
          booktitle={SLT},
          year={2024}
      }
      @article{wang2023neural,
        title={Neural codec language models are zero-shot text to speech synthesizers},
        author={Wang, Chengyi and Chen, Sanyuan and Wu, Yu and Zhang, Ziqiang and Zhou, Long and Liu, Shujie and Chen, Zhuo and Liu, Yanqing and Wang, Huaming and Li, Jinyu and others},
        journal={arXiv preprint arXiv:2301.02111},
        year={2023}
      }
    versions:
      - v1_small:
        display_name: "v1 Small"
        is_official: false
        training_hours: 585
        training_data: LibriTTS
        num_parameters: 370M
        license: "MIT"
      - v1_medium:
        display_name: "v1 Medium"
        is_official: false
        training_hours: 6000
        training_data: LibriLight
        num_parameters: 370M
        license: "MIT"
      - v2:
        display_name: "v2"
        is_official: true
        training_hours: 45000
        training_data: MLS
        num_parameters: '?M'
        license: "MIT"
  - naturalspeech2:
    display_name: "NaturalSpeech 2"
    paper: "https://arxiv.org/abs/2304.09116"
    training_data: MLS
    languages:
      - en
    training_hours: 44000
    num_parameters: 400M
    representations:
      - continuous vectors
      - waveform
    features:
      - non-autoregressive
      - grapheme-to-phoneme
      - prosody prediction
      - diffusion
    citations: >
      @inproceedings{zhang2024amphion,
          author={Zhang, Xueyao and Xue, Liumeng and Gu, Yicheng and Wang, Yuancheng and Li, Jiaqi and He, Haorui and Wang, Chaoren and Song, Ting and Chen, Xi and Fang, Zihao and Chen, Haopeng and Zhang, Junan and Tang, Tze Ying and Zou, Lexiao and Wang, Mingxuan and Han, Jun and Chen, Kai and Li, Haizhou and Wu, Zhizheng},
          title={Amphion: An Open-Source Audio, Music and Speech Generation Toolkit},
          booktitle={SLT},
          year={2024}
      }
      @article{shen2023naturalspeech,
        title={Naturalspeech 2: Latent diffusion models are natural and zero-shot speech and singing synthesizers},
        author={Shen, Kai and Ju, Zeqian and Tan, Xu and Liu, Yanqing and Leng, Yichong and He, Lei and Qin, Tao and Zhao, Sheng and Bian, Jiang},
        journal={arXiv preprint arXiv:2304.09116},
        year={2023}
      }
    versions:
      - v1:
        display_name: "v1"
        is_official: false
        training_hours: 585
        training_data: LibriTTS
        num_parameters: 380M
        license: "MIT"
  - maskgct:
    display_name: "MaskGCT"
    paper: "https://arxiv.org/abs/2304.09116"
    training_data: Emilia
    languages:
      - en
      - zh
    training_hours: 100000
    num_parameters: 1B
    representations:
      - semantic tokens
      - w2v-bert
    features:
      - non-autoregressive
      - masked training
    citations: >
      @article{wang2024maskgct,
        title={MaskGCT: Zero-Shot Text-to-Speech with Masked Generative Codec Transformer},
        author={Wang, Yuancheng and Zhan, Haoyue and Liu, Liwei and Zeng, Ruihong and Guo, Haotian and Zheng, Jiachen and Zhang, Qiang and Zhang, Xueyao and Zhang, Shunsi and Wu, Zhizheng},
        journal={arXiv preprint arXiv:2409.00750},
        year={2024}
      }
      @inproceedings{amphion,
          author={Zhang, Xueyao and Xue, Liumeng and Gu, Yicheng and Wang, Yuancheng and Li, Jiaqi and He, Haorui and Wang, Chaoren and Song, Ting and Chen, Xi and Fang, Zihao and Chen, Haopeng and Zhang, Junan and Tang, Tze Ying and Zou, Lexiao and Wang, Mingxuan and Han, Jun and Chen, Kai and Li, Haizhou and Wu, Zhizheng},
          title={Amphion: An Open-Source Audio, Music and Speech Generation Toolkit},
          booktitle={{IEEE} Spoken Language Technology Workshop, {SLT} 2024},
          year={2024}
      }
    versions:
      - v1:
        display_name: "v1"
        is_official: true
        license: "MIT"
