---
provider_name: f5
systems:
  - f5:
    display_name: "F5-TTS"
    paper: "https://arxiv.org/abs/2410.06885"
    training_data: Emilia
    languages:
      - en
      - zh
    training_hours: 95000
    num_parameters: 335M
    representations:
      - mel-spectrogram
    features:
      - non-autoregressive
      - masked training
      - diffusion
      - flow matching
    citations: >
      @article{chen2024f5,
        title={F5-tts: A fairytaler that fakes fluent and faithful speech with flow matching},
        author={Chen, Yushen and Niu, Zhikang and Ma, Ziyang and Deng, Keqi and Wang, Chunhui and Zhao, Jian and Yu, Kai and Chen, Xie},
        journal={arXiv preprint arXiv:2410.06885},
        year={2024}
      }
    versions:
      - v1:
        display_name: "v1"
        is_official: true
        license: "MIT"
  - e2:
    display_name: "E2 TTS"
    paper: "https://arxiv.org/abs/2406.18009"
    training_data: Libriheavy
    languages:
      - en
    training_hours: 50000
    num_parameters: 335M
    representations:
      - mel-spectrogram
    features:
      - non-autoregressive
      - masked training
      - diffusion
      - flow matching
    citations: >
      @article{eskimez2024e2,
        title={E2 tts: Embarrassingly easy fully non-autoregressive zero-shot tts},
        author={Eskimez, Sefik Emre and Wang, Xiaofei and Thakker, Manthan and Li, Canrun and Tsai, Chung-Hsien and Xiao, Zhen and Yang, Hemin and Zhu, Zirun and Tang, Min and Tan, Xu and others},
        journal={arXiv preprint arXiv:2406.18009},
        year={2024}
      }
    versions:
      - v1:
        display_name: "v1"
        training_data: Emilia
        languages:
          - en
          - zh
        training_hours: 95000
        is_official: false
        license: "MIT"
        