---
provider_name: sunoai
systems:
  - bark:
    display_name: "Bark"
    url: https://github.com/suno-ai/bark
    training_data: Unknown
    training_hours: Unknown
    languages:
      - en
      - de
      - es
      - fr
      - hi
      - it
      - ja
      - ko
      - pl
      - pt
      - ru
      - tr
      - zh
    num_parameters: 240M
    representations:
      - audio codec
      - encodec
    features:
      - non-autoregressive
      - autoregressive
      - grapheme-to-phoneme
      - language modeling
    citations: >
      @misc{Bark2023,
        author = {Suno},
        title = {Bark},
        year = {2023},
        publisher = {GitHub},
        journal = {GitHub repository},
        howpublished = {\url{https://github.com/suno-ai/bark}},
        commit = {f4f32d4cd480dfec1c245d258174bc9bde3c2148}
      }
      @misc{BarkVC2023,
        author = {Mylo},
        title = {Bark Voice Cloning HuBERT Quantizer},
        year = {2023},
        publisher = {GitHub},
        journal = {GitHub repository},
        howpublished = {\url{https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer}},
        commit = {4f42e44480fb076a52ddeb1f5ec6132d3c1ad25a}
      }
    versions:
      - base_en:
        display_name: "English (Base)"
        is_official: false
        license: "MIT"
      - large_en:
        display_name: "English (Large)"
        is_official: false
        license: "MIT"
      - pl:
        display_name: "Polish"
        is_official: false
        license: "MIT"
      - de:
        display_name: "German"
        is_official: false
        license: "MIT"
      - es:
        display_name: "Spanish"
        is_official: false
        license: "MIT"
      - pt:
        display_name: "Portuguese"
        is_official: false
        license: "MIT"
      - jp:
        display_name: "Japanese"
        is_official: false
        license: "MIT"
      - tr:
        display_name: "Turkish"
        is_official: false
        license: "MIT"
      - it:
        display_name: "Italian"
        is_official: false
        license: "MIT"